version: 1
formatters:
  simple:
    format: '%(asctime)s:%(levelname)s:%(funcName)s[%(lineno)s] - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
loggers:
  consoleLogger:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: DEBUG
  handlers: [console]
